# Config File for Travis CI tests
language: node_js

node_js:
  - "6"

install:
  - npm install

script:
  - "tests/runServer.sh"

after_script:
  - "./node_modules/phantomjs/bin/phantomjs tests/console-errors-test.js"
